# Generated by Django 5.2.3 on 2025-07-14 16:49

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(max_length=100)),
                ('intensity', models.CharField(choices=[('1', 'Subtle'), ('2', 'Uncomfortable'), ('3', 'Moderate'), ('4', 'Strong'), ('5', 'Intense')], max_length=100)),
                ('journal_text', models.TextField(max_length=250)),
                ('created_at', models.DateField(default=datetime.date.today, verbose_name='Journal Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
