# Generated by Django 5.2.3 on 2025-07-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0003_alter_moodentry_intensity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moodentry",
            name="mood",
            field=models.CharField(
                choices=[
                    ("Happy", "Happy 😊"),
                    ("Sad", "Sad 😢"),
                    ("Angry", "Angry 😠"),
                    ("Anxious", "Anxious 😰"),
                    ("Calm", "Calm 😌"),
                    ("Excited", "Excited 🤩"),
                    ("Tired", "Tired 😴"),
                    ("Grateful", "Grateful 🙏"),
                    ("Other", "Other ✍️"),
                ],
                max_length=100,
            ),
        ),
    ]
